{{ if eq .Values.portalScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server-rb
subjects:
  - kind: ServiceAccount
    name: {{ .Values.portal.server.serviceAccountName }}
    namespace:  {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "litmus-portal.fullname" . }}-server
  apiGroup: rbac.authorization.k8s.io
{{ end }}
