apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace:  {{ .Values.portal-namespace }}
  labels:
    app: mongo
spec:
  replicas: {{ .Values.mongo-db.deployment.replicas }}
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo-db.deployment.image }}
          resources:
            {{- toYaml .Values.mongo-db.deployment.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.mongo-db.deployment.port }}
          imagePullPolicy: {{ .Values.mongo-db.deployment.imagePullPolicy }}
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: DB_PASSWORD
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim