apiVersion: v1
kind: Service
metadata:
  name: litmusportal-server-service
  namespace:  {{ .Values.portal-namespace }}
spec:
  type: NodePort
  ports:
    - name: graphql-server
      port: {{ .Values.portal-server.service.graphql-server.port }}
      targetPort: {{ .Values.portal-server.service.graphql-server.targetPort }}
    - name: auth-server
      port: {{ .Values.portal-server.service.auth-server.port }}
      targetPort: {{ .Values.portal-server.service.auth-server.targetPort }}
  selector:
    component: litmusportal-server