# Default values for litmus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

portal-scope: cluster
portal-namespace: "litmus"

admin-config:
  AgentScope: cluster
  DBUSER: "admin"
  DBPASSWORD: "1234"
  JWTSecret: "litmus-portal@123"
  DataBaseServer: "mongodb://mongo-service:27017"

portal-frontend:
  deployment:
    replicas: 1
    image: "litmuschaos/litmusportal-frontend:ci"
    imagePullPolicy: "Always"
    port: 80
    resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 200m
    #   memory: 400Mi
    # requests:
    #   cpu: 200m
    #   memory: 400Mi
  service:
    port: 80
    targetPort: 9091

portal-server:
  deployment:
    replicas: 1
    serviceAccountName: litmus-server-account
    graphql-server:
      image: "litmuschaos/litmusportal-server:ci"
      imagePullPolicy: "Always"
      port: 8080
      env:
        subscriber-image: "litmuschaos/litmusportal-subscriber:ci"
        argo-server-image: "argoproj/argocli:v2.9.3"
        argo-workflow-controller-image: "argoproj/workflow-controller:v2.9.3"
        argo-workflow-executor-image: "argoproj/argoexec:v2.9.3"
        litmus-operator-image: "litmuschaos/chaos-operator:1.10.0"
        litmus-runner-image: "litmuschaos/chaos-runner:1.10.0"
      resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 200m
      #   memory: 400Mi
      # requests:
      #   cpu: 200m
      #   memory: 400Mi
    auth-server:
      image: "litmuschaos/litmusportal-auth-server:ci"
      imagePullPolicy: "Always"
      port: 3000
      env:
      admin-username: "admin"
      admin-password: "litmus"
      resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 200m
      #   memory: 250Mi
      # requests:
      #   cpu: 200m
      #   memory: 250Mi
  service:
    graphql-server:
      port: 9002
      targetPort: 8080
    auth-server:
      port: 9003
      targetPort: 3000

mongo-db:
  deployment:
    replicas: 1
    image: "mongo:4.2.8"
    imagePullPolicy: "Always"
    port: 27017
    resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 200m
    #   memory: 400Mi
    # requests:
    #   cpu: 200m
    #   memory: 400Mi
  service:
    port: 27017
    targetPort: 27017
